---
- name: Create home directories for FreeIPA users
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: Copy script to server
      copy:
        src: create_homedirs.sh
        dest: /tmp/create_homedirs.sh
        mode: '0755'

    - name: Execute script
      command: /tmp/create_homedirs.sh
      register: script_output
      changed_when: "'Home-Verzeichnis' in script_output.stdout"

    - name: Show script output
      debug:
        msg: "{{ script_output.stdout_lines }}"
