---
- name: Laufwerk mit Authentifizierung mounten
  hosts: all  # Ziel-Hosts (z. B. alle Laptops)
  become: no  # Führe die Aufgaben mit Root-Rechten aus
  vars_files:
#    - cred.yml  # Lade die verschlüsselten Anmeldeinformationen

  tasks:
    - name: Mount-Punkt erstellen
      file:
        path: /mnt/mein-laufwerk
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Laufwerk in /etc/fstab eintragen (NFS mit Authentifizierung)
      mount:
        path: /mnt/mein-laufwerk
        src: 192.168.1.148:/data/shared  # Quelle des Laufwerks (NFS)
        fstype: nfs  # Dateisystemtyp (nfs oder cifs für Samba)
        opts: "username=administrator,password=Benny25!,vers=4.1"
        state: present

    - name: Laufwerk mounten
      command: mount /mnt/mein-laufwerk

    - name: Automount bei Benutzeranmeldung konfigurieren
      lineinfile:
        path: /etc/pam.d/common-session
        line: "session optional pam_mount.so"
        create: yes
      notify:
        - restart pam_mount

  handlers:
    - name: restart pam_mount
      service:
        name: pam_mount
        state: restarted
