---
- name: Mount Samba Share
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Install cifs-utils
      become: yes
      ansible.builtin.package:
        name: cifs-utils
        state: present

    - name: Create mount point directory
      ansible.builtin.file:
        path: /mnt/samba-share
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Mount Samba Share
      ansible.builtin.mount:
        path: /mnt/samba-share
        src: "//{{ samba_server_ip }}/{{ samba_share_name }}"
        fstype: cifs
        opts: "username={{ samba_username }},password={{ samba_password }},uid=1000,gid=1000,file_mode=0644,dir_mode=0755"
        state: mounted

    - name: Ensure mount point is added to /etc/fstab
      ansible.builtin.mount:
        path: /mnt/samba-share
        src: "//{{ samba_server_ip }}/{{ samba_share_name }}"
        fstype: cifs
        opts: "username={{ samba_username }},password={{ samba_password }},uid=1000,gid=1000,file_mode=0644,dir_mode=0755"
        state: present
